lst = list(map(str, input('allir hlutir sem þú villt í listann með bili á milli: ').split()))
print(lst)
txt = str(input('Einhver texti sem þú vilt: '))
print(txt)
num = int(input('Heiltölur: '))
print(num)
num2 = float(input('Kommu tölur: '))
print(num2)
boo = bool(input('True eða False, 1 eða 0: '))
print(boo)
